### ISSUE TITLE
About 3.3 Global FCN in paper

### ISSUE THREAD

**Issue by zhanglonghao1992** [tshizys/CoupleNet#1]
The paper says the global FCN collects the surrounding information by concating the original and 2 times lager proposals together then feding into the later roi-wise subnet. But I dont find that in your code..How you guys do that?

**Comment by foralliance** [comment]
the same question with u. have u solved it??

**Comment by zhanglonghao1992** [comment]
@foralliance  No..I haven't

**Comment by foralliance** [comment]
@zhanglonghao1992  thx

**Comment by zimenglan-sysu-512** [comment]
hi @zhanglonghao1992  and @foralliance,

please see https://github.com/zhaoweicai/mscnn.

**Comment by Ericargus** [comment]
@zhanglonghao1992, @foralliance  , I have the same question with you ,have u fix it? Thanks

**Comment by foralliance** [comment]
@zimenglan-sysu-512 
Could you tell me more about it. which part of ms-cnn reflects the context prior's content
many many thx
