### ISSUE TITLE
About the 1x1 conv for Norm

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [tshizys/CoupleNet#3]
hi @tshizys,

why do you try to add 1x1 conv to norm them before `sum` them together?

**Comment by zimenglan-sysu-512** [comment]
I mean `ave_cls_score_rois_local` has been class-specific score.

**Comment by yousongzhu** [comment]
hi, @zimenglan-sysu-512 , we found the outputs extracted from two branches show various of scales, but the L2 normalization will reduce the score gap between different categories. 
Please see the experiments section.

**Comment by zimenglan-sysu-512** [comment]
@tshizys 
thanks

**Comment by foralliance** [comment]
@tshizys 
why only `ave_cls_score_rois_local` is normalized? 
why `ave_bbox_pred_rois_local` is not normalized?

**Comment by yousongzhu** [comment]
@foralliance，you can also try to normalize the _ave_bbox_pred_rois_local,_ but the regression does not have the problem of "score gap" .

**Comment by foralliance** [comment]
@tshizys 
So appreciated for your reply.

Another question, according to the code,
```
layer {
    bottom: "global_cls_score"        
    bottom: "conv/local_cls_score"　　　　　
    top: "cls_score"                   　
    name: "cls_score"
    type: "Eltwise"　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
}
```
couple `global_cls_score` and `conv/local_cls_score`, at this point, only `local_cls_score` is normalized. **why not normalize global_cls_score??**

**Comment by yousongzhu** [comment]
@foralliance 
Actually the _global_cls_score_ comes from a 1x1 convolution, which has been class-specific. Adding another similar 1x1 convolution is not so significant.

**Comment by foralliance** [comment]
@tshizys
I get it!
 
In section 3.3，it is pointed out that
`Secondly, we use two convolutional layers with kernal size k×k and 1×1 respectively (k is set to the default value 7) to further abstract the global representation of RoI`

Why **these two convolution layers can further abstract the global representation of RoI**? Can you give me some explanations?
