### ISSUE TITLE
trained model download

### ISSUE THREAD

**Issue by rachelmint** [tshizys/CoupleNet#4]
I have no way to download it from baidu pan (do not have a baidu account and it is hard to even register one). Is there any other way I can download the file (dropbox, onedrive?)
Thx

**Comment by yousongzhu** [comment]
Hi, @rachelmint , please check this url: https://drive.google.com/drive/folders/1oFXmHgYcwm4ju3rZZwFIPrkTsWoVUf0t?usp=sharing

**Comment by rachelmint** [comment]
thanks a lot, the link works!
