### ISSUE TITLE
Table4 - Global FCN

### ISSUE THREAD

**Issue by foralliance** [tshizys/CoupleNet#9]
@tshizys  HI

In Table4，for **Global FCN,** it can be regarded as a Faster R-CNN. 
But the depth of roI-wise subnetwork is only two, why did it work out so well( **78.5** )?? In our common sense, roi-wise subnetwork should be very deep to be correct.

**Comment by yousongzhu** [comment]
@foralliance ,Hi, 

Actually, using two layers for roi-wise subnetwork is enough to encode the features in our experiments (also in FPN and Mask R-CNN). The way of using the whole conv5 in ResNet as the roi-wise subnetwork is just to follow the early structure of Faster R-CNN.

**Comment by foralliance** [comment]
@tshizys 
thanks!!!
get it
